version: "3.8"

services:
  wpff-nginx:
    image: nginx:alpine
    container_name: wpff-web
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - /var/web_root/html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web

networks:
  web:
    external: true
